name: CI pipeline

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            pip install -r app/requirements.txt

        - name: Run tests with PYTHONPATH
          run: |
            PYTHONPATH=app pytest app/

    build-docker:
        runs-on: ubuntu-latest
        needs: test

        steps:
        - name: Checkout code
          uses: actions/checkout@v3 

        - name: Tag image
          run: docker tag mi-app:latest ${{ secrets.DOCKER_USERNAME }}/mi-app:latest
        - name: Build Docker image
          run: |
            run: docker build -t anarkatomica1996/mi-app:latest .

        - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Push image
          run: docker push anarkatomica1996/mi-app:latest